apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T04:58:12Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2320"
  uid: 7a59f6ff-9a92-4216-87e6-613224b00cfc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.54.12
  clusterIPs:
  - 10.97.54.12
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31315
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}